### ISSUE TITLE
ImageCreator

### ISSUE THREAD

**Issue by slinshady89** [slinshady89/dynamic_distortion_calibrator#8]
Because of Issues with my computer that you don't have I thought of doing a function for the next steps.
Because the BorderDetection isn't finished atm and because of the failure with my pc I worked on the next step until @ViWi92 finished the BorderDetection.
I created a debug function that assumes some arbitrary image borders. With that I'm able to find points in the same horizontal or vertical line. I write two vectors that contains all lines in that. We could test if its an horizontal or vertical line.
TODO:
Draw the Lines on the screen and save the pictures ( vertical & horizontal) in two new arrays.
Return these arrays to distortion calibration computation.

@ViWi92 do your pointer-referencing-voodoo. I tried to get the borders you'll detect later. Don't think i did it well ;)

**Comment by ghost** [comment]
Awesome idea! I'm working on the border detection, but due to always having to pass through draw function it's quite difficult to get done.

Pointer-reference-voodo done ;)
I've introduced a new struct `calibrationImage`. It contains two 2D pos arrays. One for the ground truth, aka the screen as you intend to draw it, and one for the actual image as seen by the camera. I've set and initialized two of these structs as return values for the `ImageCreator` class, namely `_vertical` and `_horizontal`.
The ground truth has currently the size of the screen and the image the size of the camera image. They are both initialized in `ImageCreator::setup()`, if you need to change that.
You can use these by doing e.g. `_vertical->groundTruth[x][y].x = someInt`.

Cheers!

**Comment by slinshady89** [comment]
Thanks for that :)

Btw I forgot that I wrote a new function that should be able to do the same like detectBrightness just for grayscale images. You'll find in commonFunctions.

we should talk about the names of our variables that we don't mix them up. I used similiar variables for the vectors with the lines in that ^^
there I used _verticals & _horizontals with an s because there are multiple lines in the vector. Lets talk about that in the next meeting.
Maybe we take vertLines and vertGT (ground truth) and vertImage or so ?
Cheers

**Comment by ghost** [comment]
Not a problem!

Oh, cool, I'll have to check it out! :)

You can rename the images within the `ImageCreator` class however you want, I just used the first thing that came to mind. You ground truth and camera image are both stored within one object of type `distortionImage`, sorry if that wasn't clear. I think _vertImage would be a good idea for a rename of the object. :)
In `DynamicDistortionCalibrator` we can keep the names, as there aren't any similiar names there. 

Cheers!

**Comment by slinshady89** [comment]
I was looking for your updates for about 20 minutes and thought about these things while writing my comment, wondering why I don't find your updates. 
I didn't pulled xD
okay then i'll rename the objects so none of us mixes them up.

**Comment by ghost** [comment]
Should be done, if not reopen.
